apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy                 # NOM du Deployment (pour les commandes kubectl)
spec:
  #replicas: 2  #j'utilise plutot hpa(horiz pod autoscaling , voir hpa.yaml)
  selector:
    matchLabels:
      app: web-app                 # pour gèrer les pods étiquetés "web-app"
  template:                        # modèle des pods à créer
    metadata:
      labels:
        app: web-app               # ÉTIQUETTE collée sur chaque pod créé
    spec:
      containers:
        - name: web-container      # NOM du conteneur dans le pod
          image: ghcr.io/stefanprodan/podinfo:6.15.0   # le logiciel (podinfo)
          ports:
            - containerPort: 9898
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9898
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9898
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi