apiVersion: v1
kind: Service
metadata:
  name: web-svc                    # NOM du Service = nom DNS dans le cluster
spec:
  selector:
    app: web-app                   # J'envoie le trafic aux pods "web-app"
  ports:
    - port: 9898                   # port du Service
      targetPort: 9898             # port du conteneur