apiVersion: v1
kind: Service
metadata:
  name: web-svc                    # NOM du Service = nom DNS dans le cluster
  labels: 
    app: web-app                  # étiquette sur le Service (pour le ServiceMonitor)
spec:
  selector:
    app: web-app                   # J'envoie le trafic aux pods "web-app"
  ports:
    - name: http                   # le ServiceMonitor désigne le port par son nom
      port: 9898                   # port du Service
      targetPort: 9898             # port du conteneur
